###
#  This action runs a small Python script that will create a Genesys Cloud email-domain-route that is associated
#  with the Archy flow we created. Since we are deploying the Archy flow independently of the CX as Code
#  (because Archy is not supported yet in CX as Code) we need to run this script as the last step before the
#  flow and its dependent objects is ready to go.
#
###
name: "Create Email Domain Route"
description: "Create Email Domain Route"
runs:
  using: "composite"
  steps:
    - run: |
        export GENESYSCLOUD_FLOW_ID=$(cat $GITHUB_WORKSPACE/output/results.json | jq -r '.output.flowInfo.id')
        python $GITHUB_WORKSPACE/blueprint/scripts/create_email_domain.py
      shell: bash
